ip_node_master: 192.168.50.115

docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg2
  - python-pip

kubernetes_dependencies:
  - kubelet
  - kubeadm
  - kubectl

token_file: join_token

services:
  - docker
  - kubelet

ports:
  - "6443/tcp"
  - "10250/tcp"
