---
- name: "Desabilitando swap"
  shell: swapoff -a
  become: true

- name: "Adicionado GPC key do kubernetes"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: "Adicionando apt repository do kubernetes"
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  become: true

- name: "Instalando dependencias"
  apt:
    update-cache: yes
    cache_valid_time: 3600
    name: "{{ item }}"
    state: latest
  with_items: "{{ kubernetes_dependencies }}"
  become: true

- name: "Startando serviços"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ services }}"

- name: "Pull das images requeridas para configuracao do kubernetes"
  shell: kubeadm config images pull
  become: true

- name: "Resetando kubeadm"
  shell: kubeadm reset -f
  register: output
  become: true

- name: "Iniciando cluster kubernetes"
  shell: kubeadm init --apiserver-advertise-address {{ ip_node_master }} --pod-network-cidr=10.244.0.0/16
  register: output
  become: true

- name: "Pegando logs e token gerado"
  local_action: copy content={{ output.stdout }} dest=~/Documentos/odin_suite/ansible/{{ token_file }}

- name: "Criando diretorio .kube"
  file:
    path: $HOME/.kube
    state: directory

- name: "Copiando o arquivo de configuracao do k8s"
  shell: sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config

- name: "Definindo permissoes"
  shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: "Definindo a variavel de ambiente"
  shell: export KUBECONFIG=/etc/kubernetes/kubelet.conf
# - name: "Instalando pod network (flanel)"
#   command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
#   become: true
